name: amazon_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4

  cupertino_icons: ^1.0.2
  firebase_core: ^2.17.0
  firebase_auth: ^4.12.1
  flutter_riverpod: ^2.4.3
  cloud_firestore: ^4.13.5
  cloud_firestore_odm: ^1.0.0-dev.80
  json_annotation: ^4.8.1
  uuid: 4.3.1

dev_dependencies:
  build_runner: ^2.4.7
  cloud_firestore_odm_generator: ^1.0.0-dev.80
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  pedantic_mono: any

flutter:
  uses-material-design: true

#cloud_firestore_odm settings
# targets:
#   $default:
#     builders:
#       json_serializable:
#         options:
#           create_field_map: true
#           create_per_field_to_json: true