// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
// /
// /

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8ruqkb8bDoYTfNSM2LxY-EXyAkp5uoYY',
    appId: '1:913865607397:web:151771915382236ee12c0c',
    messagingSenderId: '913865607397',
    projectId: 'fir-15300',
    authDomain: 'fir-15300.firebaseapp.com',
    storageBucket: 'fir-15300.appspot.com',
    measurementId: 'G-LN8TKM89FX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVKT4wP-6AUc9cZRP9beOFVylorHj_sXM',
    appId: '1:913865607397:android:256ae9781bfe266de12c0c',
    messagingSenderId: '913865607397',
    projectId: 'fir-15300',
    storageBucket: 'fir-15300.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyiNQcaz-q0rczstoaKg5Hr88hXBXYG98',
    appId: '1:913865607397:ios:8bd0ceac39e0ce39e12c0c',
    messagingSenderId: '913865607397',
    projectId: 'fir-15300',
    storageBucket: 'fir-15300.appspot.com',
    iosBundleId: 'com.example.amazonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyiNQcaz-q0rczstoaKg5Hr88hXBXYG98',
    appId: '1:913865607397:ios:6ece5fb2ab513639e12c0c',
    messagingSenderId: '913865607397',
    projectId: 'fir-15300',
    storageBucket: 'fir-15300.appspot.com',
    iosBundleId: 'com.example.amazonApp.RunnerTests',
  );
}
